### ISSUE TITLE
`FluidUMAP`: Crash if number input points < `numNeighbours  + 1`

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-core#187] opened 2022-07-10 15:00 UTC
this patch with this soundfile crash max when at point 2.5 (umap) -there must be something in the points that triggers an exception. Both in Test home compile and in Release CI compile.
[Archive.zip](https://github.com/flucoma/flucoma-core/files/9079315/Archive.zip)

**Comment by tremblap** [comment] 2022-07-10 15:05
bug report in Test mode:

Process: Max [1475]
Path: /Applications/Max.app/Contents/MacOS/Max
Identifier: com.cycling74.Max
Version: 8.2.1 [2f7eaf31afd] (8.2.1)
Code Type: X86-64 (Native)
Parent Process: ??? [1]
Responsible: Max [1475]
User ID: 501

Date/Time: 2022-07-10 14:20:03.533 +0200
OS Version: macOS 11.2.1 (20D74)
Report Version: 12
Anonymous UUID: 1CEE2877-ACA1-AF56-6B62-4814F29E546A


Time Awake Since Boot: 720 seconds

System Integrity Protection: enabled

Crashed Thread: 0 CrBrowserMain Dispatch queue: com.apple.main-thread

Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (impl::checkBounds(mDesc, args...) && "Arguments out of bounds"), function operator(), file /Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_decomposition/include/clients/nrt/../common/../../data/FluidTensor.hpp, line 568.


Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread
0 libsystem_kernel.dylib 0x00007fff2047a462 __pthread_kill + 10
1 libsystem_pthread.dylib 0x00007fff204a8610 pthread_kill + 263
2 libsystem_c.dylib 0x00007fff203fb720 abort + 120
3 libsystem_c.dylib 0x00007fff203fa9d6 __assert_rtn + 314
4 org.flucoma.fluid.libmanipulation	0x0000000134592c92 fluid::algorithm::UMAP::makeGraph(fluid::FluidDataSet<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, 1l> const&, long, Eigen::SparseMatrix<double, 0, int>&, Eigen::Ref<Eigen::Array<double, -1, -1, 0, -1, -1>, 0, Eigen::OuterStride<-1> >, bool) const + 946
5 org.flucoma.fluid.libmanipulation	0x00000001345907bd fluid::algorithm::UMAP::train(fluid::FluidDataSet<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, 1l>&, long, long, double, long, double) + 1277
6 org.flucoma.fluid.libmanipulation	0x000000013458c58f fluid::client::umap::UMAPClient::fitTransform(fluid::client::SharedClientRef<fluid::client::dataset::DataSetClient const>, fluid::client::SharedClientRef<fluid::client::dataset::DataSetClient>) + 1039

**Comment by weefuzzy** [comment] 2022-07-11 09:47
Think this is a duplicate of #104

**Comment by weefuzzy** [comment] 2022-07-11 10:03
In `makeGraph` we can see that the code assumes it can rely on there being at least `numNeighbours + 1` data points if `discardFirst` is true. 

@g-roma  I'm assuming the thing to do here, as with #104, is to add a check into `UMAPClient` that we actually have enough data points to proceed, and maybe also an assertion here in `makeGraph` ?

https://github.com/flucoma/flucoma-core/blob/804a3b39260087223f304787bcba4acce445c68b/include/algorithms/public/UMAP.hpp#L265-L283

**Closed** 2024-10-11 16:13 UTC
Labels: bug
