### ISSUE TITLE
CMake error - failed to get version string from git

### ISSUE THREAD

**Issue by Spacechild1** [flucoma/flucoma-core#5] opened 2020-06-15 10:44 UTC
Hi, when I try to run cmake I get the following error:

```
CMake Error at build/_deps/flucoma-core-src/script/flucoma_version.cmake:21 (message):
  Failed to get version string from Git
Call Stack (most recent call first):
  CMakeLists.txt:66 (include)
```

I'm on Windows 7, trying to generate a VS solution. The same thing happened with a colleague, trying to build on OSX 10.9.

Here's the full console output: 
[cmake-error.zip](https://github.com/flucoma/flucoma-sc/files/4779729/cmake-error.zip)

**Comment by Spacechild1** [comment] 2020-06-15 14:39
Thank you!

**Comment by vowelmusic** [comment] 2020-06-16 13:00
Hi, I'm trying to build on OSX 10.9.5 but I still get the error:

.../Desktop/flucoma-sc-master/build/_deps/eigen-subbuild/CMakeFiles 0
-- Found Git: /usr/local/bin/git (found version "2.23.0") 
fatal: not a git repository (or any of the parent directories): .git
CMake Error at build/_deps/flucoma-core-src/script/flucoma_version.cmake:22 (message):
  Failed to get version string from Git
Call Stack (most recent call first):
  CMakeLists.txt:66 (include)



Console output:
CMakeOutput.log.zip


The flucoma_version.cmake has updated:

# Part of the Fluid Corpus Manipulation Project (http://www.flucoma.org/)
# Copyright 2017-2019 University of Huddersfield.
# Licensed under the BSD-3 License.
# See license.md file in the project root for full license information.
# This project has received funding from the European Research Council (ERC)
# under the European Union’s Horizon 2020 research and innovation programme
# (grant agreement No 725899).

include_guard()

find_package(Git REQUIRED)

execute_process( 
  COMMAND ${GIT_EXECUTABLE} describe --abbrev=0 --always
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
  RESULT_VARIABLE result
  OUTPUT_VARIABLE FLUID_VERSION_TAG
  OUTPUT_STRIP_TRAILING_WHITESPACE  
)

if(result)
  message(FATAL_ERROR "Failed to get version string from Git")
endif()

configure_file("${CMAKE_CURRENT_LIST_DIR}/FluidVersion.hpp.in" "${CMAKE_CURRENT_LIST_DIR}/FluidVersion.hpp" @ONLY)
set(FLUID_VERSION_PATH ${CMAKE_CURRENT_LIST_DIR})

**Comment by vowelmusic** [comment] 2020-06-16 13:02
[CMakeOutput.log](https://github.com/flucoma/flucoma-core/files/4786717/CMakeOutput.log)
Sorry, I'm new to this.

**Comment by vowelmusic** [comment] 2020-06-16 14:30
Hi, I'm trying to build on OSX 10.9.5 but I still get the error:
`.../Desktop/flucoma-sc-master/build/_deps/eigen-subbuild/CMakeFiles 0
-- Found Git: /usr/local/bin/git (found version "2.23.0")
fatal: not a git repository (or any of the parent directories): .git
CMake Error at build/_deps/flucoma-core-src/script/flucoma_version.cmake:22 (message):
Failed to get version string from Git
Call Stack (most recent call first):
CMakeLists.txt:66 (include)`

Many thanks.

Console output:
[CMakeOutput.log](https://github.com/flucoma/flucoma-core/files/4787109/CMakeOutput.log)

The flucoma_version.cmake has updated:
`execute_process(
COMMAND ${GIT_EXECUTABLE} describe --abbrev=0 --always
WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
RESULT_VARIABLE result
OUTPUT_VARIABLE FLUID_VERSION_TAG
OUTPUT_STRIP_TRAILING_WHITESPACE
)`

**Comment by weefuzzy** [comment] 2020-06-16 14:41
@vowelmusic That's curious. 

Ok, first hypothesis – if there's maybe a space in the absolute path, then maybe git still ends up executing somewhere unhelpful. In the `flucoma-version.cmake`, does anything change if you add quotes around the working directory? i.e. 
```cmake
WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
```

Unfortunately the CMakeOutput.log doesn't contain much about this (it's mostly detailed stuff about figuring out compiler settings). However, if when you run CMake you redirect stderr to file, there might be a clue 
```
cmake .. 2> output.txt 
```

**Comment by vowelmusic** [comment] 2020-06-16 15:12
I added quotes and executed
`cmake -DSC_PATH=<location of your SC source> ..`
// does the process automatically skip the files which have already 
// been built? - I'm new
`fatal: not a git repository (or any of the parent directories): .git
CMake Error at build/_deps/flucoma-core-src/script/flucoma_version.cmake:22 (message):
  Failed to get version string from Git
Call Stack (most recent call first):
  CMakeLists.txt:66 (include)`

> if when you run CMake you redirect stderr to file
I don't understand this

When I executed
`cmake .. 2> output.txt`
I got
`-- Populating flucoma-core
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/vowel/Desktop/flucoma-sc-master/build/_deps/flucoma-core-subbuild
/Applications/CMake.app/Contents/bin/cmake -S/Users/vowel/Desktop/flucoma-sc-master/build/_deps/flucoma-core-subbuild -B/Users/vowel/Desktop/flucoma-sc-master/build/_deps/flucoma-core-subbuild --check-build-system CMakeFiles/Makefile.cmake 0
/Applications/CMake.app/Contents/bin/cmake -E cmake_progress_start /Users/vowel/Desktop/flucoma-sc-master/build/_deps/flucoma-core-subbuild/CMakeFiles /Users/vowel/Desktop/flucoma-sc-master/build/_deps/flucoma-core-subbuild//CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -s -f CMakeFiles/Makefile2 all
[ 11%] Performing update step for 'flucoma-core-populate'
[ 22%] No patch step for 'flucoma-core-populate'
[ 33%] No configure step for 'flucoma-core-populate'
[ 44%] No build step for 'flucoma-core-populate'
[ 55%] No install step for 'flucoma-core-populate'
[ 66%] No test step for 'flucoma-core-populate'
[ 77%] Completed 'flucoma-core-populate'
[100%] Built target flucoma-core-populate
/Applications/CMake.app/Contents/bin/cmake -E cmake_progress_start /Users/vowel/Desktop/flucoma-sc-master/build/_deps/flucoma-core-subbuild/CMakeFiles 0
-- Populating hisstools
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/vowel/Desktop/flucoma-sc-master/build/_deps/hisstools-subbuild
/Applications/CMake.app/Contents/bin/cmake -S/Users/vowel/Desktop/flucoma-sc-master/build/_deps/hisstools-subbuild -B/Users/vowel/Desktop/flucoma-sc-master/build/_deps/hisstools-subbuild --check-build-system CMakeFiles/Makefile.cmake 0
/Applications/CMake.app/Contents/bin/cmake -E cmake_progress_start /Users/vowel/Desktop/flucoma-sc-master/build/_deps/hisstools-subbuild/CMakeFiles /Users/vowel/Desktop/flucoma-sc-master/build/_deps/hisstools-subbuild//CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -s -f CMakeFiles/Makefile2 all
[ 11%] Performing update step for 'hisstools-populate'
[ 22%] No patch step for 'hisstools-populate'
[ 33%] No configure step for 'hisstools-populate'
[ 44%] No build step for 'hisstools-populate'
[ 55%] No install step for 'hisstools-populate'
[ 66%] No test step for 'hisstools-populate'
[ 77%] Completed 'hisstools-populate'
[100%] Built target hisstools-populate
/Applications/CMake.app/Contents/bin/cmake -E cmake_progress_start /Users/vowel/Desktop/flucoma-sc-master/build/_deps/hisstools-subbuild/CMakeFiles 0
-- Populating eigen
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/vowel/Desktop/flucoma-sc-master/build/_deps/eigen-subbuild
/Applications/CMake.app/Contents/bin/cmake -S/Users/vowel/Desktop/flucoma-sc-master/build/_deps/eigen-subbuild -B/Users/vowel/Desktop/flucoma-sc-master/build/_deps/eigen-subbuild --check-build-system CMakeFiles/Makefile.cmake 0
/Applications/CMake.app/Contents/bin/cmake -E cmake_progress_start /Users/vowel/Desktop/flucoma-sc-master/build/_deps/eigen-subbuild/CMakeFiles /Users/vowel/Desktop/flucoma-sc-master/build/_deps/eigen-subbuild//CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -s -f CMakeFiles/Makefile2 all
[ 11%] Performing update step for 'eigen-populate'
[ 22%] No patch step for 'eigen-populate'
[ 33%] No configure step for 'eigen-populate'
[ 44%] No build step for 'eigen-populate'
[ 55%] No install step for 'eigen-populate'
[ 66%] No test step for 'eigen-populate'
[ 77%] Completed 'eigen-populate'
[100%] Built target eigen-populate
/Applications/CMake.app/Contents/bin/cmake -E cmake_progress_start /Users/vowel/Desktop/flucoma-sc-master/build/_deps/eigen-subbuild/CMakeFiles 0
-- Configuring incomplete, errors occurred!
See also "/Users/vowel/Desktop/flucoma-sc-master/build/CMakeFiles/CMakeOutput.log".`

Thanks.

**Comment by weefuzzy** [comment] 2020-06-16 15:47
>  I'm new

Sorry, I'll do my best to be clear. 

> does the process automatically skip the files which have already been built? 

Yes, but it's not yet at the point of building anything. There are three broad steps here: configuring (figuring out what to build, and how to do it); building and installing. At this point it's still configuring. The other libraries we need are downloaded, and then it's failing on a step where it generates a new source code file with the current version in it. It seems to be failing because when it runs `git` to recover the current version, `git` is executing in the wrong folder. 

> `cmake -DSC_PATH=<location of your SC source> ..`

Apologies, because this might be a stupid question (but I want to be sure of the steps you're taking): is that the literal command you're running? If so, I don't know if it accounts for this problem, but it certainly won't work. `<location of your SC source>` is intended to be replaced with the path to the Supercollider source code, e.g. on my machine I use `cmake -DSC_PATH=~/dev/supercollider ..` 

> > if when you run CMake you redirect stderr to file

> I don't understand this

When stuff gets printed to the terminal, there's actually two 'streams', one called `stdout`, the other called `stderr`. When we do `> out.txt` that says to redirect a stream to a file, instead of the screen. In the case of CMake, the more detailed stuff about its progress goes to the second of these streams (stderr), and to get that we have to do `2> out.txt` instead. 

Anyway, I'm still slightly baffled by what might be causing it to misbehave here because your output looks happy enough right up until the point it fails. If you have the patience, one thing to try might be to junk all the build files and try running CMake again from a clean folder. Unfortunately this will involve it doing the download steps again. 

If you delte the `build` folder you made (or just everything in it), and run CMake again, do you see any change? If not, we'll have to start getting more forensic!

**Comment by vowelmusic** [comment] 2020-06-16 16:30
Thanks for explaining!

> Apologies, because this might be a stupid question (but I want to be sure of the steps you're taking): is that the literal command you're running?

I may have done something stupid elsewhere but I have the correct path & 
have successfully run cmake using the 01aBoringMixer in the SC examples.

> If you have the patience, one thing to try might be to junk all the build files and try running CMake again from a clean folder. 

Yes, I was doing this with each attempt before 
but figured it needed the edited cmake file.
Tried again with the same error.

Guess: could it be anything to do with my clang?
`Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)`
Is there an instruction I need to send from Terminal to make it C++14 compliant?

Thanks again.

**Comment by weefuzzy** [comment] 2020-06-16 17:33
A slightly horrible thought just ocurred to me whilst I was trying to work out what could possibly be causing this: did you download the `flucoma-sc` source via a zip file? 

I've just confirmed that this file (auto generated by Github), strips out all the version control information, which would explain why this command is failing even with the explicit working directory I added. 

If that is what you did, would you be able to try cloning directly instead? You can do it from the command line like 
```
git clone https://github.com/flucoma/flucoma-sc.git
```
and this will make  a new source sub-folder for you. 

If this is the cause we'll need to rehink our assumption that there will be a git folder available at compile time. 

> Guess: could it be anything to do with my clang?
`Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)`
Is there an instruction I need to send from Terminal to make it C++14 compliant?

You should be fine with that version of clang from what I can tell. clang 3.5 claims complete C++14 support, and all the necessary flags are enabled by CMake (once it actually gets to the end of a run!)

**Comment by vowelmusic** [comment] 2020-06-16 18:13
Thanks, yes it was from the zip file.
I executed the git command (cd=Desktop?)
`-bash: /usr/bin/git: No such file or directory`
Does current directory need to be something else?

**Comment by Spacechild1** [comment] 2020-06-16 18:17
cd anywhere and then clone the project with `git clone URL https://github.com/flucoma/flucoma-sc.git`

**Comment by vowelmusic** [comment] 2020-06-16 18:21
I do have a git alias in usr/local/bin
(w/ -osxkeychain, -cvsserver, -shell, k)
there is a usr/local/git dir
In usr/bin:
~cvsserver, -receive-pack, -shell, -system, -archive, upload-pack

...if this helps

**Comment by vowelmusic** [comment] 2020-06-16 18:22
same error
`-bash: /usr/bin/git: No such file or directory`

**Comment by vowelmusic** [comment] 2020-06-16 18:26
Should I create a directory /usr/bin/git ?

**Comment by Spacechild1** [comment] 2020-06-16 18:31
If you execute `git`, you should get something like this:
```
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```
If not, then your git installation is messed up. First clean up the installation (if necessary, install from scratch), then we can proceed.

**Comment by weefuzzy** [comment] 2020-06-16 18:55
You shouldn't need to create any special directories...

git must be working at some level, because CMake managed to download the other libraries, for which it uses git. From your first post, I can see that CMake located git in `/usr/local/` 

Simply typing `git` on the command line should give the output @Spacechild1 pasted above. If it doesn't then maybe the terminal isn't searching `usr/local/` for commands. If you run 
```bash 
echo $PATH
```
what do you get?

**Comment by vowelmusic** [comment] 2020-06-16 18:55
Sorry - I hadn't restarted Terminal!
I have cloned the project & run cmake successfully :)
`-- Configuring done
-- Generating done
-- Build files have been written to: /Users/vowel/Desktop/flucoma-sc/build`
Is there another command to install?

**Comment by vowelmusic** [comment] 2020-06-16 18:58
*I meant build

**Comment by Spacechild1** [comment] 2020-06-16 19:00
now you just have to type `make` and wait :-)

**Comment by weefuzzy** [comment] 2020-06-16 19:00
@vowelmusic brilliant. Thanks for sticking with it! 

The next bit is to build, then install. Which should work if, from the build folder, you run 
```bash 
make install
```
This will compile everything (which will take a few minutes), and then run the install steps. After that, there should be a folder `flucoma-sc/install/FludCorpusManipulation` that you can copy to your Supercollider extensions directory. 

I'll make a new issue for this problem with the generated zip files vs. my assumptions about the universe

**Comment by vowelmusic** [comment] 2020-06-16 19:06
mmm?
`1 warning and 16 errors generated.
make[2]: *** [src/FluidAmpGate/CMakeFiles/FluidAmpGate.dir/FluidAmpGate.cpp.o] Error 1
make[1]: *** [src/FluidAmpGate/CMakeFiles/FluidAmpGate.dir/all] Error 2
make: *** [all] Error 2
Lewiss-Mac-Pro:build vowel$ `

**Comment by Spacechild1** [comment] 2020-06-16 19:14
try to do `make VERBOSE=1` instead and post the output.

**Comment by vowelmusic** [comment] 2020-06-16 19:52
same error

**Comment by Spacechild1** [comment] 2020-06-16 20:05
are you sure? `make VERBOSE=1` should give you the verbose output of the console... Please post the *whole* console output as a .zip file.

**Comment by vowelmusic** [comment] 2020-06-16 20:10
This is what Terminal showed
[TerminalOutput.zip](https://github.com/flucoma/flucoma-core/files/4788881/TerminalOutput.zip)

**Comment by Spacechild1** [comment] 2020-06-16 20:26
thanks! there are a couple of compilation errors. just wait for @wefuzzy to have a look.

**Comment by vowelmusic** [comment] 2020-06-16 21:21
👍

**Comment by weefuzzy** [comment] 2020-06-17 09:25
@Spacechild1  thanks for your help. @vowelmusic  I'll need to have a look at this: the compiler error makes no sense!

I'm going to close this issue because the original problem is fixed. There are two new ones, for building from the source zip and building with Xcode 6.

**Closed by weefuzzy** 2020-06-17 09:25 UTC
Labels: bug
